apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: isu8tsshd-go-gitops
  description: This is GitOps manifest for isu8tsshd-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=isu8tsshd-go
    backstage.io/kubernetes-id: isu8tsshd-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: isu8tsshd-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:isu8tsshd-go
