apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: isu8tsshd-go
  janus-idp.io/tekton: isu8tsshd-go
  backstage.io/kubernetes-id: isu8tsshd-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: isu8tsshd-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
